### ISSUE TITLE
ERDについて

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/Topics#1]
topic_block_settingsについて、blockごとじゃなくて、frameごとのような気がします。
もくもく会で相談させてください。

**Comment by kteraguchi** [comment]
frame毎に修正済み

**Comment by s-nakajima** [comment]
寺口さん、
topic_frame_settingsがframe_idになっていますが、frame_idで良いのですか？
言語毎で設定が変わることはないので、frame_keyが正しいのではないですか。
※search_boxesの方は、frame_keyとなっています。

**Comment by s-nakajima** [comment]
寺口さん、
topic_frame_settingsがframe_idになっていますが、frame_idで良いのですか？
言語毎で設定が変わることはないので、frame_keyが正しいのではないですか。
※search_boxesの方は、frame_keyとなっています。

**Comment by s-nakajima** [comment]
https://github.com/NetCommons3/Topics/issues/37 のため、close
