### ISSUE TITLE
特殊文字の変換

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/Topics#14]
&nbsp;が表示されます。
（WYSIWYGエディタに空行を入れると&nbsp;が登録されます。）

https://github.com/NetCommons3/Topics/blob/e9ab7e3015322b386bad48255d2420f638aa4444/View/Topics/index.ctp#L121
HtmlHelper::linkメソッドのオプションにhtmlspecialcharsしない指定ができた気がします。

https://github.com/NetCommons3/Topics/blob/e9ab7e3015322b386bad48255d2420f638aa4444/View/Topics/index.ctp#L131
h関数使用しなければ良いと思います。

前処理でstrip_tagsしているので、XSS攻撃は大丈夫かと。

**Comment by s-nakajima** [comment]
https://github.com/NetCommons3/Topics/issues/37 のため、close
