### ISSUE TITLE
権限の検索条件について

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/Topics#16]
https://github.com/NetCommons3/Topics/blob/e9ab7e3015322b386bad48255d2420f638aa4444/Model/Topic.php#L181

作成権限（contentCreatable）の条件がないです。
ブログが参考になると思います。
https://github.com/NetCommons3/Blogs/blob/111fbf996168d66e9c15d55cafd2a6a0b7c243b2/Model/BlogEntry.php#L160

また、ブロック毎に権限が違うため、
参照可能なブロック分ORでつなげるか、権限毎にブロックのIN句を付けるかだと思います。
処理速度を考えると、IN句の方が早い気がします。

**Comment by s-nakajima** [comment]
https://github.com/NetCommons3/Topics/issues/37 のため、close
