### ISSUE TITLE
不要なファイル

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/Topics#17]
bakeで作成されたViewファイル（ctp）が残っているようです。
削除しといてほしいです。

また、
https://github.com/NetCommons3/SearchBoxes/blob/master/View/Elements/SearchBoxes/advanced_search.ctp
https://github.com/NetCommons3/Search/blob/master/Model/Behavior/SearchableBehavior.php
使用していない気がします。

あと、
https://github.com/NetCommons3/Search/blob/master/Utility/Search.php
をTopicsプラグインに持ってきて、Searchプラグインを削除したいです。

**Comment by s-nakajima** [comment]
https://github.com/NetCommons3/Topics/issues/37 のため、close
