### ISSUE TITLE
対象期間のカレンダーの表示がおかしい

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/Topics#2]
対象期間のカレンダーの表示がおかしいです。
キャプチャを添付します。

![default](https://cloud.githubusercontent.com/assets/4422735/9174547/7832f528-3fbb-11e5-978c-707fa8bdbff4.png)

**Comment by topaz2** [comment]
SingletonViewBlockHtmlHelper 絡みだったので寺口さんにお願いしておきました。
以下 skype のやりとり。

[8/12/15, 7:46:42 PM] Jun Nishikawa: お疲れ様です。
この件なのですが、SingletonViewBlockHtmlHelper の挙動がなんかおかしいみたいです。
https://github.com/NetCommons3/Topics/issues/2
[8/12/15, 7:50:22 PM] Jun Nishikawa: app/Plugin/NetCommons/View/Elements/common_css.ctp
に直接
'/components/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css'
を追加するとちゃんと表示されるんですが
app/Plugin/NetCommons/View/Elements/datetimepicker.ctp
側で css を指定すると
<link rel="stylesheet" type="text/css" href="/css/.css">
<link rel="stylesheet" type="text/css" href="/css/1.css">
みたいな tag しか出てこないので。
[8/12/15, 7:52:55 PM] Jun Nishikawa: 取り急ぎ common_css.ctp 側に指定することで直しておきました。

**Comment by s-nakajima** [comment]
了解です。

**Comment by kteraguchi** [comment]
日付要素を使用しているViewファイル（ctp）で、
echo $this->element('NetCommons.datetimepicker');
を記述すると解決します。

common_js.ctpやcommon_css.ctp側で指定しなくても大丈夫です。

**Comment by kteraguchi** [comment]
センター以外に配置すると、datetimepicker読み込まれないですね。
Pageプラグインのレイアウト機能改修の影響と思われます。

Pageプラグインで吸収するように検討しますので、
echo $this->element('NetCommons.datetimepicker');
を記述する方法でアップしといてください。

**Comment by s-nakajima** [comment]
https://github.com/NetCommons3/Topics/issues/37 のため、close
